services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    depends_on:
      - postgres
      - redis
    volumes:
      - symfony_cache:/app/var/cache

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: '!ChangeMe!'
      POSTGRES_USER: app
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  symfony_cache: